/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CACDULIEU.SinhVien;
import DBEngine.DBEngine;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class MeNuSinhVien extends javax.swing.JFrame {
    private String maSV;
    ArrayList<SinhVien> dsSV=new ArrayList<>(); // ds luu tru sinh vien 
    static final String fileNameDSSV="SinhVien.txt";
    DBEngine DBE=new DBEngine();
    
    void loadFileDSSV(){
        try {
           dsSV=(ArrayList<SinhVien>) DBE.docFile(fileNameDSSV);
        } catch (Exception ex) {
            System.out.println(ex.toString());
           JOptionPane.showMessageDialog(this,ex);
        }
        
    }
    
    
    public void checkLogin(){
        if(maSV==null){
            JOptionPane.showMessageDialog(this,"Bạn cần đăng nhập để thực hiện chức năng này");
            dispose(); // close window
            setVisible(false);
            System.exit(0); // stop program
        }
    }
    
    void sayHelloLogin(){
        checkLogin();
        try {
            for(SinhVien it:dsSV){
                if(it.getMaSinhVien().equalsIgnoreCase(maSV)){
                    lb_xinChao.setText("Xin Chào Sinh Viên: "+ it.getHoTen());
                    break;
                }
            }
        
        } catch (Exception e) {
            System.err.println("say Hellog Login : "+ e.toString());
        }
       
    }
   
    /**
     * Creates new form MeNuSinhVien
     */
    public MeNuSinhVien() {
        initComponents();
        loadFileDSSV();
        sayHelloLogin();
        this.setLocationRelativeTo(null) ;
    }
    
    public MeNuSinhVien(String maSV) {
        this.maSV = maSV;
        initComponents();
        loadFileDSSV();
        sayHelloLogin();
        this.setLocationRelativeTo(null) ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_xinChao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_trangChu = new javax.swing.JMenu();
        menu_xem = new javax.swing.JMenu();
        menu_xemTKB = new javax.swing.JMenuItem();
        menu_dangKy = new javax.swing.JMenu();
        menu_dangKiHP = new javax.swing.JMenuItem();
        menu_hoTro = new javax.swing.JMenu();
        menu_rutDangKiHP = new javax.swing.JMenuItem();
        menu_thoat = new javax.swing.JMenu();
        menu_dangXuat = new javax.swing.JMenuItem();
        menu_Thoat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_xinChao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb_xinChao.setText("Xin Chào Sinh Viên");

        menu_trangChu.setText("Trang chu");
        jMenuBar1.add(menu_trangChu);

        menu_xem.setText("Xem");
        menu_xem.setToolTipText("");

        menu_xemTKB.setText("Xem thoi khoa bieu");
        menu_xemTKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_xemTKBActionPerformed(evt);
            }
        });
        menu_xem.add(menu_xemTKB);

        jMenuBar1.add(menu_xem);

        menu_dangKy.setText("Đăng kí");
        menu_dangKy.setActionCommand("");

        menu_dangKiHP.setText("Dang ki hoc phan");
        menu_dangKiHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_dangKiHPActionPerformed(evt);
            }
        });
        menu_dangKy.add(menu_dangKiHP);

        jMenuBar1.add(menu_dangKy);

        menu_hoTro.setText("Ho tro");

        menu_rutDangKiHP.setText("Rut dang ki hoc phan");
        menu_hoTro.add(menu_rutDangKiHP);

        jMenuBar1.add(menu_hoTro);

        menu_thoat.setText("Thoát");

        menu_dangXuat.setText("Dang xuat");
        menu_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_dangXuatActionPerformed(evt);
            }
        });
        menu_thoat.add(menu_dangXuat);

        menu_Thoat.setText("Thoat");
        menu_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ThoatActionPerformed(evt);
            }
        });
        menu_thoat.add(menu_Thoat);

        jMenuBar1.add(menu_thoat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(lb_xinChao)
                .addGap(242, 242, 242))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lb_xinChao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_xemTKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_xemTKBActionPerformed
        // TODO add your handling code here:
        XemLichHoc xemlh=new XemLichHoc(maSV);
        xemlh.setVisible(true);
        dispose();
    }//GEN-LAST:event_menu_xemTKBActionPerformed

    private void menu_dangKiHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_dangKiHPActionPerformed
        // TODO add your handling code here:
        DKHocPhan dkhp=new DKHocPhan(this.maSV);
        dkhp.setVisible(true);
        dispose();
    }//GEN-LAST:event_menu_dangKiHPActionPerformed

    private void menu_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_dangXuatActionPerformed
        // TODO add your handling code here:
        DangNhap DN=new DangNhap();
        DN.setVisible(true);
        dispose();
    }//GEN-LAST:event_menu_dangXuatActionPerformed

    private void menu_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menu_ThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeNuSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeNuSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeNuSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeNuSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeNuSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lb_xinChao;
    private javax.swing.JMenuItem menu_Thoat;
    private javax.swing.JMenuItem menu_dangKiHP;
    private javax.swing.JMenu menu_dangKy;
    private javax.swing.JMenuItem menu_dangXuat;
    private javax.swing.JMenu menu_hoTro;
    private javax.swing.JMenuItem menu_rutDangKiHP;
    private javax.swing.JMenu menu_thoat;
    private javax.swing.JMenu menu_trangChu;
    private javax.swing.JMenu menu_xem;
    private javax.swing.JMenuItem menu_xemTKB;
    // End of variables declaration//GEN-END:variables
}
