/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CACDULIEU.GiangVien;
import CACDULIEU.LopHocPhan;
import CACDULIEU.HocPhan;
import DBEngine.DBEngine;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import DAO.HocPhanDAO;
import DAO.LopHocPhanDAO;

/**
 *
 * @author ADMIN
 */
public class QLLopHocPhan extends javax.swing.JFrame {

    static ArrayList<HocPhan> dshp= new ArrayList<>();
    static ArrayList<GiangVien> dsgv= new ArrayList<>();
    static ArrayList<LopHocPhan> dslhp= new ArrayList<>();
    static LopHocPhan lhp= new LopHocPhan();
    static String fileHP="HocPhan.txt";
    static String fileLHP="LopHocPhan.txt";
    static String fileGV="GiangVien.txt";
    static DBEngine DBE=new DBEngine();
    String mahp="";
    String magv="";
    int dong=-1;
    /**
     * Creates new form QLLopHocPhan
     */
    public QLLopHocPhan() {
        initComponents();
        loadfieHP();
        loadfieLHP();
        loadfieGV();
        loadcb1();
        loadcb();
        loadtb();
        
    }
    void loadfieGV(){
        try {
           dsgv=(ArrayList<GiangVien>) DBE.docFile(fileGV);
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(this,ex);
        }
    }
    void loadfieHP(){
        try {
           dshp=(ArrayList<HocPhan>) DBE.docFile(fileHP);
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(this,ex);
        }
    }
    void loadfieLHP(){
        try {
           dslhp=(ArrayList<LopHocPhan>) DBE.docFile(fileLHP);
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(this,ex);
        }
    }
    void nhapfileLHP(){
        try {
            DBE.LuuFile(fileLHP, dslhp);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,ex);
        }
    }
    void loadcb(){
        jComboxMaHocPhan.removeAllItems();
       for(var it:dshp)
            jComboxMaHocPhan.addItem(it.getTenHocPhan()); 
    }
    void loadcb1(){
        jComboGV.removeAllItems();
       for(var it:dsgv)
            jComboGV.addItem(it.getTenGiangVien()); 
    }
    void loadtb(){
        jTableLHP.setModel(new LopHocPhanDAO(dslhp));
    }
    boolean kiemtra(String kt){
       boolean x=true;
       for (var it:dslhp){
           if(it.getMaLopHocPhan().trim().equals(kt.trim()))
               x=false;
       } 
       return  x;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLHP = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextMaLHP = new javax.swing.JTextField();
        jComboxMaHocPhan = new javax.swing.JComboBox<>();
        jTextTietDay = new javax.swing.JTextField();
        jTextNgayHoc = new javax.swing.JTextField();
        jTextNgayBD = new javax.swing.JTextField();
        jTextDD = new javax.swing.JTextField();
        jButtonThem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboGV = new javax.swing.JComboBox<>();
        jButtonql = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Quản Lý Lớp Học Phần");

        jTableLHP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTableLHP);

        jLabel2.setText("Mã Lớp Học Phần");

        jLabel3.setText("Tên Học Phần");

        jLabel4.setText("Tiết Dạy");

        jLabel5.setText("Ngày Học");

        jLabel6.setText("Ngày Bắt Đầu Học ");

        jLabel7.setText("Địa Điểm");

        jTextMaLHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMaLHPActionPerformed(evt);
            }
        });

        jComboxMaHocPhan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboxMaHocPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboxMaHocPhanActionPerformed(evt);
            }
        });

        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });

        jButtonSua.setText("Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jLabel8.setText("Giảng Viên");

        jComboGV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGVActionPerformed(evt);
            }
        });

        jButtonql.setText("Quay Lại");
        jButtonql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonqlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextMaLHP, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jComboxMaHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jComboGV, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextTietDay, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonql)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonThem)
                                .addGap(24, 24, 24))
                            .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextNgayHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextDD, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jButtonThem)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonSua)
                                .addGap(32, 32, 32)
                                .addComponent(jButtonXoa)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextMaLHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboxMaHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTietDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNgayHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButtonql)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextMaLHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMaLHPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMaLHPActionPerformed

    private void jComboxMaHocPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboxMaHocPhanActionPerformed
        // TODO add your handling code here:
        
        String tenlop=(String) jComboxMaHocPhan.getSelectedItem();
        for(var it:dshp){
            if(it.getTenHocPhan().equals(tenlop))
                mahp=it.getMaHocPhan();
        }
        
    }//GEN-LAST:event_jComboxMaHocPhanActionPerformed

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
        // TODO add your handling code here:
        if(jTextMaLHP.getText().trim().equals("") ||jTextTietDay.getText().trim().equals("") ||jTextNgayHoc.getText().trim().equals("") ||jTextNgayBD.getText().trim().equals("") || jTextDD.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Chua du thong tin de them");
        }else{
            if(kiemtra(jTextMaLHP.getText())){
                lhp = new LopHocPhan(jTextMaLHP.getText(),mahp,magv, jTextTietDay.getText(),jTextNgayHoc.getText(),jTextNgayBD.getText(),jTextDD.getText());
                dslhp.add(lhp);
                nhapfileLHP();
                loadtb();
            }
            else{
                JOptionPane.showMessageDialog(this,"Đã Tồn Tại Mã :"+jTextMaLHP.getText());
            }
        }
    }//GEN-LAST:event_jButtonThemActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        // TODO add your handling code here:
        dong = jTableLHP.getSelectedRow();
        if(dong !=-1){
        if(jTextMaLHP.getText().trim().equals("") ||jTextTietDay.getText().trim().equals("") ||jTextNgayHoc.getText().trim().equals("") ||jTextNgayBD.getText().trim().equals("") || jTextDD.getText().trim().equals("")){
                JOptionPane.showMessageDialog(this,"Chua du thong tin de them");
            }else{
                if(kiemtra(jTextMaLHP.getText())==false){
                    if(jTextMaLHP.getText().trim().equals(dslhp.get(dong).getMaLopHocPhan().trim())){
                        lhp = new LopHocPhan(jTextMaLHP.getText(),mahp,magv, jTextTietDay.getText(),jTextNgayHoc.getText(),jTextNgayBD.getText(),jTextDD.getText());
                        dslhp.set(dong,lhp);
                        nhapfileLHP();
                        loadtb();
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Đã có mã: "+jTextMaLHP.getText()+" Ở một dòng khác");
                    }
                }
                else{
                    lhp = new LopHocPhan(jTextMaLHP.getText(),mahp,magv, jTextTietDay.getText(),jTextNgayHoc.getText(),jTextNgayBD.getText(),jTextDD.getText());
                    dslhp.set(dong,lhp);
                    nhapfileLHP();
                    loadtb();
                }
            }
        }
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        // TODO add your handling code here:
        dong= jTableLHP.getSelectedRow();
        if(dong != -1){
            dslhp.remove(dong);
            nhapfileLHP();
            loadtb();
            
        }
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jComboGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGVActionPerformed
        // TODO add your handling code here:
        String ten=(String) jComboGV.getSelectedItem();
        for(var it:dsgv){
            if(it.getTenGiangVien().equals(ten))
                magv=it.getMaGiangVien();
        }
    }//GEN-LAST:event_jComboGVActionPerformed

    private void jButtonqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonqlActionPerformed
        // TODO add your handling code here:
        MeNuQuanLy MN= new MeNuQuanLy();
        MN.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonqlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLLopHocPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLLopHocPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLLopHocPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLLopHocPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLLopHocPhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JButton jButtonql;
    private javax.swing.JComboBox<String> jComboGV;
    private javax.swing.JComboBox<String> jComboxMaHocPhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLHP;
    private javax.swing.JTextField jTextDD;
    private javax.swing.JTextField jTextMaLHP;
    private javax.swing.JTextField jTextNgayBD;
    private javax.swing.JTextField jTextNgayHoc;
    private javax.swing.JTextField jTextTietDay;
    // End of variables declaration//GEN-END:variables
}
