/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CACDULIEU.DangKy;
import CACDULIEU.HocPhan;
import CACDULIEU.LopHocPhan;
import DAO.XemLichHocDAO;
import java.util.ArrayList;
import DBEngine.DBEngine;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author ADMIN
 */
public class XemLichHoc extends javax.swing.JFrame {
    private String maSV;
    static DBEngine DBE=new DBEngine(); // khoi tao bien doc ghi file
    
    ArrayList<DangKy> dsdkall =new ArrayList<DangKy>(); // danh sach dang ky tat ca
    
    ArrayList<DangKy> dsdk = new ArrayList<DangKy>(); // danh sách dang ky theo ma sv
    
    ArrayList<LopHocPhan> dsLhp = new ArrayList<LopHocPhan>(); // danh sach lop hoc phan
    
    ArrayList<HocPhan> dshp = new ArrayList<HocPhan>();     // danh sach hoc phan
    
    static final String filelhp="LopHocPhan.txt";
    static final String filehp="HocPhan.txt";
    static final String fileDK="DangKy.txt";
    int dong=-1;

    public XemLichHoc(String maSV) { 
        this.maSV = maSV;
        initComponents();
        checkLogin();
        loadFileHP();
        loadFileLHP();
        loadFiledk();
        loadTable();
        this.setLocationRelativeTo(null) ;
        txt_MSV.setText(maSV);
    }
    

   
    
    
    void loadFileLHP(){
        try {
           dsLhp=(ArrayList<LopHocPhan>) DBE.docFile(filelhp);
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(this,ex);
        }
    }
    void loadFileHP(){
        try {
           dshp=(ArrayList<HocPhan>) DBE.docFile(filehp);
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(this,ex);
        }
    }
    
    void loadFiledk(){
        try {
            
           dsdkall=(ArrayList<DangKy>) DBE.docFile(fileDK);
           ArrayList<DangKy> dsdktem =new ArrayList<>();
            for (DangKy it:dsdkall) {
                System.out.println(it.getMaSinhVien());
                if( it.getMaSinhVien()!=null && it.getMaSinhVien().equals(maSV)){
                    dsdktem.add(it);
                }
            }

           dsdk=dsdktem;
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(this,ex);
            System.out.println(ex.toString());
        }
    }
    void nhapfile(){
        try {
            DBE.LuuFile(fileDK, dsdkall);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,ex);
        }
    }
    void loadTable(){
        jTable1.setModel(new XemLichHocDAO(dsLhp,dshp,dsdk));
    }
    /**
     * Creates new form XemLichHoc
     */
    
    public void checkLogin(){
        if(this.maSV==null){
            JOptionPane.showMessageDialog(this,"Bạn cần đăng nhập để thực hiện chức năng này");
            dispose(); // close window
            setVisible(false);
            System.exit(0); // stop program
        }
    }
    
    public XemLichHoc() {
        initComponents();
        checkLogin();
//        loadFileHP();
//        loadFileLHP();
//        loadFiledk();
//        loadTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_HuyDangKy = new javax.swing.JButton();
        btn_DangKyHocPhan = new javax.swing.JButton();
        jButtonQL = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_MSV = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_trangChu = new javax.swing.JMenu();
        menu_xem = new javax.swing.JMenu();
        menu_xemTKB = new javax.swing.JMenuItem();
        menu_dangKy = new javax.swing.JMenu();
        menu_dangKiHP = new javax.swing.JMenuItem();
        menu_hoTro = new javax.swing.JMenu();
        menu_rutDangKiHP = new javax.swing.JMenuItem();
        menu_thoat = new javax.swing.JMenu();
        menu_dangXuat = new javax.swing.JMenuItem();
        menu_Thoat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Xem Lịch Học ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btn_HuyDangKy.setText("Hủy Đăng Ký");
        btn_HuyDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyDangKyActionPerformed(evt);
            }
        });

        btn_DangKyHocPhan.setText("Đến Đăng Ký Học Phần");
        btn_DangKyHocPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangKyHocPhanActionPerformed(evt);
            }
        });

        jButtonQL.setText("Quay Lại");
        jButtonQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQLActionPerformed(evt);
            }
        });

        jLabel2.setText("MSV");

        txt_MSV.setEnabled(false);

        menu_trangChu.setText("Trang chu");
        jMenuBar1.add(menu_trangChu);

        menu_xem.setText("Xem");
        menu_xem.setToolTipText("");

        menu_xemTKB.setText("Xem thoi khoa bieu");
        menu_xemTKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_xemTKBActionPerformed(evt);
            }
        });
        menu_xem.add(menu_xemTKB);

        jMenuBar1.add(menu_xem);

        menu_dangKy.setText("Đăng kí");
        menu_dangKy.setActionCommand("");

        menu_dangKiHP.setText("Dang ki hoc phan");
        menu_dangKiHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_dangKiHPActionPerformed(evt);
            }
        });
        menu_dangKy.add(menu_dangKiHP);

        jMenuBar1.add(menu_dangKy);

        menu_hoTro.setText("Ho tro");

        menu_rutDangKiHP.setText("Rut dang ki hoc phan");
        menu_hoTro.add(menu_rutDangKiHP);

        jMenuBar1.add(menu_hoTro);

        menu_thoat.setText("Thoát");

        menu_dangXuat.setText("Dang xuat");
        menu_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_dangXuatActionPerformed(evt);
            }
        });
        menu_thoat.add(menu_dangXuat);

        menu_Thoat.setText("Thoat");
        menu_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ThoatActionPerformed(evt);
            }
        });
        menu_thoat.add(menu_Thoat);

        jMenuBar1.add(menu_thoat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btn_DangKyHocPhan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonQL)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_HuyDangKy)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_MSV, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_HuyDangKy)
                    .addComponent(btn_DangKyHocPhan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonQL)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txt_MSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HuyDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyDangKyActionPerformed
        // TODO add your handling code here:
        dong= jTable1.getSelectedRow();
        if(dong!=-1){
            dsdkall.remove(dsdk.get(dong));
            nhapfile();
            loadFiledk();
            loadTable();
        }
    }//GEN-LAST:event_btn_HuyDangKyActionPerformed

    private void btn_DangKyHocPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangKyHocPhanActionPerformed
        // TODO add your handling code here:
        DKHocPhan dkhp=new DKHocPhan(maSV);
        
        dkhp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_DangKyHocPhanActionPerformed

    private void jButtonQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQLActionPerformed
        // TODO add your handling code here:
        MeNuSinhVien menusv=new MeNuSinhVien(this.maSV);
       
        menusv.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonQLActionPerformed

    private void menu_xemTKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_xemTKBActionPerformed
        // TODO add your handling code here:
        XemLichHoc xemlh=new XemLichHoc(maSV);
        xemlh.setVisible(true);
        dispose();
    }//GEN-LAST:event_menu_xemTKBActionPerformed

    private void menu_dangKiHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_dangKiHPActionPerformed
        // TODO add your handling code here:
        DKHocPhan dkhp=new DKHocPhan(this.maSV);
        dkhp.setVisible(true);
        dispose();
    }//GEN-LAST:event_menu_dangKiHPActionPerformed

    private void menu_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_dangXuatActionPerformed
        // TODO add your handling code here:
        DangNhap DN=new DangNhap();
        DN.setVisible(true);
        dispose();
    }//GEN-LAST:event_menu_dangXuatActionPerformed

    private void menu_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menu_ThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemLichHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemLichHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemLichHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemLichHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemLichHoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DangKyHocPhan;
    private javax.swing.JButton btn_HuyDangKy;
    private javax.swing.JButton jButtonQL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem menu_Thoat;
    private javax.swing.JMenuItem menu_dangKiHP;
    private javax.swing.JMenu menu_dangKy;
    private javax.swing.JMenuItem menu_dangXuat;
    private javax.swing.JMenu menu_hoTro;
    private javax.swing.JMenuItem menu_rutDangKiHP;
    private javax.swing.JMenu menu_thoat;
    private javax.swing.JMenu menu_trangChu;
    private javax.swing.JMenu menu_xem;
    private javax.swing.JMenuItem menu_xemTKB;
    private javax.swing.JTextField txt_MSV;
    // End of variables declaration//GEN-END:variables
}
